export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";

export const FETCH_SINGLE_NEWS_REQUEST = "FETCH_SINGLE_NEWS_REQUEST";
export const FETCH_SINGLE_NEWS_SUCCESS = "FETCH_SINGLE_NEWS_SUCCESS";
export const FETCH_SINGLE_NEWS_ERROR = "FETCH_SINGLE_NEWS_ERROR";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";